# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=nginx

before_install:
  - sudo apt update
  - sudo apt list --upgradable
  - sudo apt --only-upgrade -y install docker-ce

script:
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" .
