# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=scratch

before_install:
  - docker pull tecnativa/docker-socket-proxy

script:
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" .
  - docker run -dit --name="$DEMYX_REPOSITORY" demyx/"$DEMYX_REPOSITORY"
  - docker exec "$DEMYX_REPOSITORY" haproxy -v

after_success:
  - bash travis.sh
