# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=nginx DEBIAN_FRONTEND=noninteractive

before_install:
  - apt update
  - apt upgrade
  - docker pull alpine
  - docker pull demyx/mariadb
  - docker pull demyx/wordpress
  - docker pull demyx/wordpress:cli
  - docker pull demyx/utilities
  - docker network create demyx

script:
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" .
  - docker run -d --name=demyx_db --network=demyx -e DEMYX_DATABASE=demyx -e DEMYX_USERNAME=demyx -e DEMYX_PASSWORD=demyx -e DEMYX_ROOT_PASSWORD=demyx demyx/mariadb
  - docker run -d --name=demyx_wp --network=demyx -v demyx_wp:/demyx -e DEMYX_DB_HOST=demyx_db -e DEMYX_DB_NAME=demyx -e DEMYX_DB_USER=demyx -e DEMYX_DB_PASSWORD=demyx demyx/wordpress
  - sleep 5
  - docker run --network=demyx --volumes-from=demyx_wp --workdir=/demyx demyx/wordpress:cli core install --url=http://localhost --title=demyx --admin_user=demyx --admin_password=demyx --admin_email=info@domain.tld --skip-email
  - docker run -dit --name="$DEMYX_REPOSITORY" --network=demyx -v demyx_wp:/demyx -e DEMYX_WORDPRESS=true -e DEMYX_WORDPRESS_CONTAINER=demyx_wp -e DEMYX_WORDPRESS_CONTAINER_PORT=9000 -e DEMYX_DOMAIN=localhost demyx/"$DEMYX_REPOSITORY"
  - sleep 5
  - docker exec "$DEMYX_REPOSITORY" sh -c "wget -qO- http://localhost | grep 'Hello world'"
