# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=scratch

before_install:
  - docker pull alpine

script:
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" .
  - docker run -d --rm --name et demyx/"$DEMYX_REPOSITORY"
  - docker exec -t et etserver --version
